name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 

    - name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: cwillhelm2/go-webserver-demo

    - name: Build and Push image to Docker Hub 
      uses: docker/build-push-action@v2
      with: 
     #   context: ./...
        tags: |
          cwillhelm2/go-webserver-demo:${{ github.event.head_commit.message }}
          ${{ steps.metdata.outputs.tags }}

        # build on feature branches, only push on main branch 
        push: ${{ github.ref == 'refs/heads/main' }}
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
